services:
  redis:
    image: redis:7.4.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: "note"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL:      jdbc:postgresql://db:5432/note
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST:          redis
      SPRING_REDIS_PORT:          "6379"

volumes:
  redis-data:
  pgdata: